### ISSUE TITLE
Does this still work? (question for users)

### ISSUE THREAD

**Issue by SheepCommander** [TrueXPixels/powercord-message-tooltips#9]
I don't quite know what's supposed to change lol

**Comment by lorencerri** [comment]
Yes, it does still work; I've updated the preview on the README, but here it is as well:

|        Title         |                 Preview                 |
| :------------------: | :-------------------------------------: |
|     Color Codes      | ![](https://i.imgur.com/BWgytsA.gif) |
| Base64<sup>[1]</sup> <br> **[Experimental]** | ![](https://i.imgur.com/IH8QKeQ.gif) |

**Comment by SheepCommander** [comment]
Ohhhhh coool
